# .graphclientrc.yml
sources:
  - name: uniswapv2
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/37633/secreth_goerli_subgraph/0.420.69
plugins:
  - pollingLive:
      defaultInterval: 100